module.exports = function () {
  var data = {
    citas: [
      {
        id: 1,
        date: "2023-04-10",
        client_id: 24,
        PsychologistID: 35,
        AppointStatusID: 3343,

      },
      {
        id: 2,
        date: "2023-04-10",
        client_id: 21,
        PsychologistID: 31,
        AppointStatusID: 3113,

      },
      {
        id: 3,
        date: "2023-04-10",
        client_id: 23,
        PsychologistID: 132,
        AppointStatusID: 32,

      },
    ],
    clients: [
      {
        id: 1,
        userName: "Ricardo14",
        password: "holaMundo",
        names: "Cesar Ricardo",
        lastNames: "Rodriguez Ccorahua",
        emailAddress: "ricardito12hola@gmail.com",
        phoneNumber: "976238462",
        age: 23,
        UserStatus_id: 1,
        Gender_id: 1,
      },
      {
        id: 2,
        userName: "Miguelaso",
        password: "adiosMiguel",
        names: "Miguel Angel",
        lastNames: "Huaman Sosa",
        emailAddress: "miguelito15as@gmail.com",
        phoneNumber: "956336482",
        age: 25,
        UserStatus_id: 1,
        Gender_id: 1,
      },
      {
        id: 3,
        userName: "Marcos15",
        password: "messi23fw",
        names: "Marcos Alonso",
        lastNames: "Salinas Cotrina",
        emailAddress: "mymessi10best@gmail.com",
        phoneNumber: "994233461",
        age: 33,
        UserStatus_id: 1,
        Gender_id: 1,
      },
      {
        id: 4,
        userName: "princesa12",
        password: "rockstarforever",
        names: "Angela Jimena",
        lastNames: "Valenzuela Hoyos",
        emailAddress: "siemprehappy15@gmail.com",
        phoneNumber: "956438361",
        age: 20,
        UserStatus_id: 1,
        Gender_id: 2,
      },
    ],
    reviews: [
      {
        id: 1,
        content: "excelente servicio",
        date: "2023-04-10",
        likes: 4,
        Client_id: 2,
        Psychologist_id: 3,
      },
      {
        id: 2,
        content: "trato muy agradable",
        date: "2022-07-22",
        likes: 3,
        Client_id: 4,
        Psychologist_id: 2,
      },
      {
        id: 3,
        content: "muy recomendado",
        date: "2022-02-18",
        likes: 5,
        Client_id: 4,
        Psychologist_id: 1,
      },
    ],
    psychologists: [
      {
        id: 1,
        userName: "Jorge",
        password: "170902jorge",
        names: "Jorge Miguel",
        lastNames: "Chavez Perez",
        emailAddress: "jorge.h.iguel@gmail.com",
        phoneNumber: "917081429",
        age: 27,
        rating: 4,
        UserStatus_Id: 1,
        Gender_id: "Masculino",
        specialty:
        {
          id: 1,
          name: "psicología clínica",
          description: "rama de la psicología que se enfoca en el diagnóstico, tratamiento y prevención de trastornos mentales y emocionales, y en la promoción del bienestar psicológico.",
        },
      },
      {
        id: 2,
        userName: "Estela",
        password: "213402estel",
        names: "Esteli Rosa",
        lastNames: "Serna Huamani",
        emailAddress: "estelita.y.tuo@gmail.com",
        phoneNumber: "963233429",
        age: 37,
        rating: 3,
        UserStatus_Id: 2,
        Gender_id: "Femenino",
        specialty:
        {
          id: 1,
          name: "psicología clínica",
          description: "rama de la psicología que se enfoca en el diagnóstico, tratamiento y prevención de trastornos mentales y emocionales, y en la promoción del bienestar psicológico.",
        },
      }

    ],
    payments: [
      {
        id: 1,
        paymentCode: "BV100-1746456",
        idAppointment: 1,
        cardNumber: "4236178832453296",
        date: "2023-04-10",
        currency: "Soles",
        import: 64.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 234,
        expiration: "2023-07-08",
        email: "jhon1999@gmail.com",
      },
      {
        id: 2,
        paymentCode: "BV100-1746566",
        idAppointment: 2,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 58.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 284,
        expiration: "2023-07-08",
        email: "julian1992@gmail.com",
      },
      {
        id: 3,
        paymentCode: "BV100-1746659",
        idAppointment: 3,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "maria1996@gmail.com",
      },
      {
        id: 4,
        paymentCode: "BV100-1746678",
        idAppointment: 4,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "ferale2000@gmail.com",
      },
      {
        id: 5,
        paymentCode: "BV100-1746678",
        idAppointment: 5,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "ferale2000@gmail.com",
      },
      {
        id: 6,
        paymentCode: "BV100-1746678",
        idAppointment: 6,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "ferale2000@gmail.com",
      },
      {
        id: 7,
        paymentCode: "BV100-1746678",
        idAppointment: 7,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "ferale2000@gmail.com",
      },
      {
        id: 8,
        paymentCode: "BV100-1746678",
        idAppointment: 8,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "ferale2000@gmail.com",
      },
      {
        id: 9,
        paymentCode: "BV100-1746678",
        idAppointment: 9,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "ferale2000@gmail.com",
      },
      {
        id: 10,
        paymentCode: "BV100-1746678",
        idAppointment: 10,
        cardNumber: "4236178832453567",
        date: "2023-04-12",
        currency: "Soles",
        import: 62.00,
        name: "Jhon Alejandro",
        lastname: "Deza Mendoza",
        cvv: 884,
        expiration: "2023-07-08",
        email: "ferale2000@gmail.com",
      },
    ],
    specialties: [
      {
        id: 1,
        name: "psicología clínica",
        description: "rama de la psicología que se enfoca en el diagnóstico, tratamiento y prevención de trastornos mentales y emocionales, y en la promoción del bienestar psicológico.",
      },
      {
        id: 2,
        name: "psicología clínica",
        description: "rama de la psicología que se enfoca en el diagnóstico, tratamiento y prevención de trastornos mentales y emocionales, y en la promoción del bienestar psicológico.",
      },
      {
        id: 3,
        name: "psicología clínica",
        description: "rama de la psicología que se enfoca en el diagnóstico, tratamiento y prevención de trastornos mentales y emocionales, y en la promoción del bienestar psicológico.",
      },
    ],
  };
  return data;
};
